# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='image_url',
            field=models.CharField(default='https://www.shareicon.net/download/128x128/2016/11/14/851937_stack_512x512.png', max_length=200),
        ),
    ]
