# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170903_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Author'),
            preserve_default=False,
        ),
    ]
