# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_repository_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
