# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170903_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.CharField(default='https://www.shareicon.net/download/128x128/2016/11/14/851937_stack_512x512.png', max_length=200),
        ),
    ]
